### ISSUE TITLE
线上怎么部署

### ISSUE THREAD

**Issue by hushenao** [wmui/vueblog#11]
我想用你的这个整体结构写一个线上的项目，我之前看到底部有一个线上部署的教程，可以给我发一个吗，参考一下，

**Comment by wmui** [comment]
@hushenao 
[nodejs服务器部署教程一](https://segmentfault.com/a/1190000010098126)
[nodejs服务器部署教程二，把vue项目部署到线上](https://segmentfault.com/a/1190000010205995)
[nodejs服务器部署教程三，部署基于node+vue+mongodb的项目](https://segmentfault.com/a/1190000010213434)
[nodejs服务器部署教程四，部署ssl证书，升级为https](https://segmentfault.com/a/1190000010281512)
