### ISSUE TITLE
nmp run build 没有index

### ISSUE THREAD

**Issue by hushenao** [wmui/vueblog#12]
npm run build 生成的dist文件夹里面没有index.html
![image](https://user-images.githubusercontent.com/23112269/29760928-1b8be91a-8bf9-11e7-80cf-4c27a5d508fd.png)
配置文件没有修改，只是把关于数据库的东西给删掉了，因为我只负责前端的部分

**Comment by MinWest** [comment]
同问

**Comment by wmui** [comment]
#11
