### ISSUE TITLE
你好，项目跑起来没有默认数据怎么回事？需要自己创建吗

### ISSUE THREAD

**Issue by fuerpeng** [wmui/vueblog#20]
![image](https://user-images.githubusercontent.com/24818415/35150309-ed174b4c-fd54-11e7-8ed3-410f37107267.png)

**Comment by fuerpeng** [comment]
![image](https://user-images.githubusercontent.com/24818415/35150462-69314caa-fd55-11e7-9cc3-9421244e3674.png)

**Comment by wmui** [comment]
@fuerpeng 需要在本地开启数据库服务，登录后可进后台添加文章

**Comment by fuerpeng** [comment]
@wmui 谢谢你的回复，数据库服务我开了，不过你看我后面的截图我没有发现登录页面。

**Comment by fuerpeng** [comment]
已经解决了  在浏览器中先访问  http://127.0.0.1:3000/login
