### ISSUE TITLE
登录博客发表文章后无法退出

### ISSUE THREAD

**Issue by Kuohao-wu** [wmui/vueblog#23]
**经过排查，是登录的action axios路径设置错了**
![image](https://user-images.githubusercontent.com/16506726/40521465-623780de-5ffe-11e8-8566-e68abfdf676c.png)

**修改成baseUrl即可**
![image](https://user-images.githubusercontent.com/16506726/40521484-7fbdb68c-5ffe-11e8-873c-cd143a4bbd18.png)

**Comment by wmui** [comment]
@Kuohao-wu 感谢指出，已修复
