### ISSUE TITLE
bug：前端ajax请求头里面既没有带cookie也没有带token

### ISSUE THREAD

**Issue by jczzq** [wmui/vueblog#29]
浏览器：360浏览器
版本： v9.5
内核版本：Chrome 63.0

我启动项目登录后，前端所有的ajax请求包括打标签、创建文章等需要token的请求头里面既没有带上cookie也没有带上token，导致后端checkToken处理时全部返回的“Please login”。

**Comment by wmui** [comment]
@jczzq http://127.0.0.1:3000访问，不要用localhost。用360测试了没有问题。默认是携带cookie的
![2018-07-12_100652](https://user-images.githubusercontent.com/24876474/42608710-af181732-85bb-11e8-86b7-0a7ab909970b.png)

**Comment by wmui** [comment]
使用127.0.0.1访问，不要用localhost。用360测试了没有问题，默认是携带cookie的

![2018-07-12_100652](https://user-images.githubusercontent.com/24876474/42608911-b2e58e3e-85bc-11e8-921e-458d1c53fc45.png)

**Comment by jczzq** [comment]
可以了，给个建议：监听0.0.0.0或者应用host与请求host分离开
