### ISSUE TITLE
后台登录失败

### ISSUE THREAD

**Issue by JiangChenYang** [wmui/vueblog#3]
第一次进入后台后，再打开浏览器进去后台还有验证登录， 点击登录没有跳转到管理后台

**Comment by wmui** [comment]
@JiangChenYang 你好，方便的话可否截取个gif图，以便查看和解决问题

**Comment by JiangChenYang** [comment]
854240709 我的qq可以加下一起看看

**Comment by wmui** [comment]
未提供详细错误信息
