### ISSUE TITLE
2.3.0 局域网 访问失败

### ISSUE THREAD

**Issue by yoog568** [wmui/vueblog#30]
您好，使用2.3.0版本本地电脑部署成功，可是为什么在手机访问电脑ip+port确实不通？手机和电脑明明是在一个局域网中的

**Comment by yoog568** [comment]
我换端口号也不行

**Comment by yoog568** [comment]
我config中的改为    host: '192.168.0.106'  就可以了，可是为什么

**Comment by wmui** [comment]
config中的host是全局配置的，你监听127.0.0.1，局域网是肯定访问不了的
