### ISSUE TITLE
修改service.js和app.js到正式域名后，执行pm2 start ecosystem.json --env production报错

### ISSUE THREAD

**Issue by raymondzhangl** [wmui/vueblog#7]
执行pm2 logs vueblog后报以下错误
0|vueblog  | Error: Cannot find module './dist/vue-ssr-server-bundle.json'
0|vueblog  |     at Function.Module._resolveFilename (module.js:469:15)
0|vueblog  |     at Function.Module._load (module.js:417:25)
0|vueblog  |     at Module.require (module.js:497:17)
0|vueblog  |     at require (internal/module.js:20:19)
0|vueblog  |     at Object.<anonymous> (/vueblog/server.js:53:18)
0|vueblog  |     at Module._compile (module.js:570:32)
0|vueblog  |     at Object.Module._extensions..js (module.js:579:10)
0|vueblog  |     at Module.load (module.js:487:32)
0|vueblog  |     at tryModuleLoad (module.js:446:12)
0|vueblog  |     at Function.Module._load (module.js:438:3)

**Comment by wmui** [comment]
@raymondzhangl 是否已经执行`npm run build`打包，项目是部署在服务器上的吗

**Comment by raymondzhangl** [comment]
这个问题已经解决，我是个js新手，原因是没有执行npm run build打包。
现在遇到一个新的问题。nginx配置好，pm2 启动后，访问域名，pm log报错
0|vueblog  | error during render : /index
0|vueblog  | undefined
0|vueblog  | Error: Not implemented: window.scrollTo
0|vueblog  |     at module.exports ( /vueblog/node_modules/_jsdom@11.1.0@jsdom/lib/jsdom/browser/not-implemented.js:9:17)
0|vueblog  |     at Window.scrollTo ( /vueblog/node_modules/_jsdom@11.1.0@jsdom/lib/jsdom/browser/Window.js:448:7)
0|vueblog  |     at Vue$3.<anonymous> ( /vueblog/node_modules/_vue-router@2.7.0@vue-router/dist/vue-router.common.js:1535:14)
0|vueblog  |     at Array.<anonymous> ( /vueblog/node_modules/_vue@2.4.2@vue/dist/vue.runtime.common.js:699:14)
0|vueblog  |     at nextTickHandler ( /vueblog/node_modules/_vue@2.4.2@vue/dist/vue.runtime.common.js:646:16)
0|vueblog  |     at runMicrotasksCallback (internal/process/next_tick.js:58:5)
0|vueblog  |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
0|vueblog  |     at process._tickDomainCallback (internal/process/next_tick.js:122:9) undefined

浏览器端报404错误，请问这个可能是什么原因呢？

**Comment by wmui** [comment]
@raymondzhangl 删除dist目录，执行npm run dev看看是否能通过域名访问，如果可以说明nginx配置正常。然后执行npm run build，npm run start，看看能否正常访问。最后执行`pm2 delete vueblog`删除原来的，然后执行`pm2 start ecosystem.json --env production`
