### ISSUE TITLE
本地运行错误，不知什么原因

### ISSUE THREAD

**Issue by Simmon12** [wmui/vueblog#8]
按照您的说明，node的版本是8.4.0，但是运行后出现如下错误，求指教
`webpack built 4bf6e1050eae9eecd060 in 10597ms
error during render : /
undefined`
然后打开localhost:8080是
500|Interval Server Error

**Comment by wmui** [comment]
@Simmon12 是否已经开启本地的mongodb?

**Comment by Simmon12** [comment]
是的， 已经开启本地的mongodb

**Comment by wmui** [comment]
@Simmon12 我本地一直跑的v7.7.4，刚才特意切换到v8.4.0测试了下，确实有报错。我是这样解决的：
1. 删除原来的node_modules
2. 设置npm淘宝源，不然安装node-sass报错
```
npm config set registry https://registry.npm.taobao.org --global
npm config set disturl https://npm.taobao.org/dist --global
```
3. 执行npm install,npm run build,npm run start就跑起来了。

**Comment by wmui** [comment]
@Simmon12 由于我是切换node版本导致的错误，所以可能和你遇到的不一样。经测试，直接使用v8.4.0运行项目是正常的

**Comment by Simmon12** [comment]
本地运行还是运行不起来
`server started at localhost:8080   
                            
error during render : /                                              
undefined                                                            
error during render : /                                              
TypeError: Cannot read property 'data' of undefined                  
    at server-bundle.js:1:3325                                       
    at <anonymous>                                                   
    at process._tickCallback (internal/process/next_tick.js:188:7)   `

**Comment by wmui** [comment]
整个项目删除，重新clone线上的。
